#!/bin/bash

# ABSTRACT: this script wraps the puppet apply command for scripted execution

# * --detailed-exitcodes:
#  Provide extra information about the run via exit codes. If enabled, 'puppet
#  apply' will use the following exit codes:
#
#  0: The run succeeded with no changes or failures; the system was already in
#  the desired state.
#
#  1: The run failed.
#
#  2: The run succeeded, and some resources were changed.
#
#  4: The run succeeded, and some resources failed.
#
#  6: The run succeeded, and included both changes and failures.

PUPPET_BIN=`which puppet`

$PUPPET_BIN apply --detailed-exitcodes --color=false $*
rc="$?"

if [ "$rc" -eq "0" -o "$rc" -eq "2" ] ; then
  echo "puppet exited with code $rc: success"
  exit 0
else
  echo "puppet exited with code $rc: failure"
  exit 1
fi

